# Generated by Django 6.1 on 2026-08-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='background_color',
            field=models.CharField(default='#f6f7f9', max_length=7),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/banners/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/logos/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='primary_color',
            field=models.CharField(default='#111827', max_length=7),
        ),
    ]
