# Generated by Django 6.1 on 2026-08-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_background_color_restaurant_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='accepts_delivery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='accepts_pickup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='accepts_table_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='estimated_time_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='minimum_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
