# Generated by Django 6.1 on 2026-09-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurant_accepts_delivery_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_order__gte', 0)), name='restaurant_minimum_order_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_fee__gte', 0)), name='restaurant_delivery_fee_non_negative'),
        ),
    ]
