# Generated by Django 6.1 on 2026-09-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_alter_restaurant_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='body_font',
            field=models.CharField(blank=True, default='Poppins', max_length=100, verbose_name='Fonte do corpo'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='card_bg_color',
            field=models.CharField(default='#FFF9F2', max_length=7, verbose_name='Cor de fundo dos cards'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='text_color',
            field=models.CharField(default='#1F2937', max_length=7, verbose_name='Cor do texto'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='title_color',
            field=models.CharField(default='#D22A2A', max_length=7, verbose_name='Cor dos títulos'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='title_font',
            field=models.CharField(blank=True, default='Playfair Display', max_length=100, verbose_name='Fonte dos títulos'),
        ),
    ]
