# Generated by Django 6.1 on 2026-09-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_restaurant_body_font_restaurant_card_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_name_font',
            field=models.CharField(blank=True, default='Playfair Display', max_length=100, verbose_name='Fonte do nome do restaurante'),
        ),
    ]
