# Generated by Django 6.1 on 2026-09-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_restaurant_restaurant_name_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='shortcut_bg_color',
            field=models.CharField(default='rgba(255, 255, 255, 0.05)', max_length=30, verbose_name='Cor de fundo dos atalhos de categoria'),
        ),
    ]
