# Generated by Django 6.1 on 2026-09-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_restaurant_shortcut_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_name_italic',
            field=models.BooleanField(default=True, verbose_name='Nome do restaurante em itálico'),
        ),
    ]
