# Generated by Django 6.1 on 2026-09-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_restaurant_restaurant_name_italic'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='product_detail_bg',
            field=models.CharField(default='#FFFFFF', max_length=30, verbose_name='Cor de fundo da página de produto'),
        ),
    ]
