# Generated by Django 6.1 on 2026-10-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_restaurant_product_detail_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Formato: 5564999999999 (com código do país e DDD, só números)', max_length=20, verbose_name='WhatsApp do restaurante'),
        ),
    ]
