# Generated by Django 6.1 on 2026-10-04 15:00

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_restaurant_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='pix_key',
            field=models.CharField(blank=True, help_text='CPF, CNPJ, telefone, email ou chave aleatória.', max_length=100, verbose_name='Chave Pix'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='pix_qrcode',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='QR Code do Pix'),
        ),
    ]
