# Generated by Django 6.1 on 2026-10-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_restaurant_pix_key_restaurant_pix_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='facebook',
            field=models.CharField(blank=True, help_text='URL completa (ex: https://facebook.com/pizzarianapoli)', max_length=200, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='instagram',
            field=models.CharField(blank=True, help_text='Só o @usuário (ex: @pizzarianapoli)', max_length=100, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tiktok',
            field=models.CharField(blank=True, help_text='Só o @usuário (ex: @pizzarianapoli)', max_length=100, verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.URLField(blank=True, verbose_name='Site próprio'),
        ),
    ]
