# Generated by Django 6.1 on 2026-10-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_restaurant_facebook_restaurant_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_name_border_color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Cor da borda do nome'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_name_color',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Cor do nome do restaurante'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_name_has_border',
            field=models.BooleanField(default=False, verbose_name='Nome com borda'),
        ),
    ]
