# Generated by Django 6.1 on 2026-10-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_restaurant_restaurant_name_border_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='printer_name',
            field=models.CharField(blank=True, default='Microsoft Print to PDF', help_text='Nome exato da impressora instalada no Windows.', max_length=200, verbose_name='Nome da impressora'),
        ),
    ]
