# Generated by Django 6.1 on 2026-08-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_productingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='productingredient',
            name='unit',
            field=models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilograma'), ('G', 'Grama'), ('L', 'Litro'), ('ML', 'Mililitro')], default='UN', max_length=10),
        ),
    ]
