# Generated by Django 6.1 on 2026-08-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_productingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='supplier',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
