# Generated by Django 6.1 on 2026-09-02 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_purchase_cancelled_at_purchase_cancelled_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='inventory.purchase'),
        ),
    ]
