# Generated by Django 6.1 on 2026-09-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_order_order_type'),
        ('inventory', '0010_alter_purchase_restaurant_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productingredient',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='product_ingredient_quantity_positive'),
        ),
    ]
