# Generated by Django 6.1 on 2026-08-24 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productvariation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_choices', models.PositiveIntegerField(default=0)),
                ('max_choices', models.PositiveIntegerField(default=1)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_groups', to='catalog.product')),
            ],
            options={
                'ordering': ['position', 'name'],
                'constraints': [models.UniqueConstraint(fields=('product', 'name'), name='unique_addon_group_name_per_product')],
            },
        ),
    ]
