# Generated by Django 6.1 on 2026-08-25 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_addon'),
        ('restaurants', '0002_restaurantmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(max_length=20)),
                ('order_type', models.CharField(choices=[('pickup', 'Retirada'), ('delivery', 'Entrega'), ('table', 'Mesa')], max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'Novo'), ('CONFIRMED', 'Confirmado'), ('PREPARING', 'Em preparo'), ('READY', 'Pronto'), ('OUT_FOR_DELIVERY', 'Saiu para entrega'), ('FINISHED', 'Finalizado'), ('REJECTED', 'Recusado'), ('CANCELLED', 'Cancelado')], default='NEW', max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('address_number', models.CharField(blank=True, max_length=20)),
                ('complement', models.CharField(blank=True, max_length=150)),
                ('table_number', models.PositiveIntegerField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='restaurants.restaurant')),
            ],
        ),
    ]
