# Generated by Django 6.1 on 2026-08-25 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_name', models.CharField(max_length=100)),
                ('addon_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='catalog.orderitem')),
            ],
        ),
    ]
