# Generated by Django 6.1 on 2026-08-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_order_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_time_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
