# Generated by Django 6.1 on 2026-08-28 21:59

import uuid

from django.db import migrations, models


def generate_public_tokens(apps, schema_editor):
    Order = apps.get_model("catalog", "Order")

    for order in Order.objects.all():
        order.public_token = uuid.uuid4()
        order.save(update_fields=["public_token"])


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_order_estimated_time_minutes"),
    ]

    operations = [

        # 1. Cria o campo temporariamente sem unique
        migrations.AddField(
            model_name="order",
            name="public_token",
            field=models.UUIDField(
                null=True,
                editable=False,
            ),
        ),

        # 2. Gera um UUID diferente para cada pedido já existente
        migrations.RunPython(
            generate_public_tokens,
            migrations.RunPython.noop,
        ),

        # 3. Depois torna o campo obrigatório e único
        migrations.AlterField(
            model_name="order",
            name="public_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                unique=True,
                editable=False,
            ),
        ),

    ]
