# Generated by Django 6.1 on 2026-08-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_order_public_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('picku1p', 'Retirada'), ('delivery', 'Entrega'), ('table', 'Mesa')], max_length=20),
        ),
    ]
