# Generated by Django 6.1 on 2026-08-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_processed',
            field=models.BooleanField(default=False),
        ),
    ]
