# Generated by Django 6.1 on 2026-09-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_order_stock_processed'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='addongroup',
            constraint=models.CheckConstraint(condition=models.Q(('min_choices__lte', models.F('max_choices'))), name='addon_group_min_lte_max'),
        ),
    ]
