# Generated by Django 6.1 on 2026-09-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_addongroup_addon_group_min_lte_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('pickup', 'Retirada'), ('delivery', 'Entrega'), ('table', 'Mesa')], max_length=20),
        ),
    ]
