# Generated by Django 6.1 on 2026-10-02 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_product_image'),
        ('restaurants', '0013_restaurant_product_detail_bg'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True, verbose_name='Aberta')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paga')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Aberta em')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fechada em')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_sessions', to='restaurants.restaurant')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table_sessions', to='restaurants.table')),
            ],
            options={
                'verbose_name': 'Comanda',
                'verbose_name_plural': 'Comandas',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='TableSessionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nome do produto')),
                ('variation_name', models.CharField(blank=True, max_length=200, verbose_name='Variação')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço unitário')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_items', to='catalog.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.tablesession')),
            ],
            options={
                'verbose_name': 'Item da comanda',
                'verbose_name_plural': 'Itens da comanda',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TableSessionItemAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_name', models.CharField(max_length=200, verbose_name='Nome do adicional')),
                ('addon_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço do adicional')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='catalog.tablesessionitem')),
            ],
            options={
                'verbose_name': 'Adicional do item',
                'verbose_name_plural': 'Adicionais do item',
            },
        ),
    ]
