# Generated by Django 6.1 on 2026-10-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_tablesession_tablesessionitem_tablesessionitemaddon'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesession',
            name='needs_print',
            field=models.BooleanField(default=True, verbose_name='Precisa imprimir'),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='printed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Impressa em'),
        ),
    ]
