# Generated by Django 6.1 on 2026-10-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_tablesession_needs_print_tablesession_printed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Dinheiro'), ('card', 'Cartão'), ('pix', 'Pix')], default='cash', max_length=20, verbose_name='Forma de pagamento'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago')], default='pending', max_length=20, verbose_name='Status de pagamento'),
        ),
    ]
