# Generated by Django 6.1 on 2026-10-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_order_payment_method_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_by_weight',
            field=models.BooleanField(default=False, verbose_name='Vendido por peso (kg)'),
        ),
    ]
