# Generated by Django 6.1 on 2026-10-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_product_is_by_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesessionitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Peso (kg)'),
        ),
    ]
