# Generated by Django 6.1 on 2026-10-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_tablesessionitem_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Dinheiro'), ('credit', 'Cartão de Crédito'), ('debit', 'Cartão de Débito'), ('pix', 'Pix')], default='cash', max_length=20, verbose_name='Forma de pagamento'),
        ),
    ]
